require 'thread'
require 'sexpistol'
require_relative 'cirrocumulus/identifier'
require_relative 'cirrocumulus/channels'
require_relative 'cirrocumulus/facts'
require_relative 'cirrocumulus/ontology'
require_relative 'cirrocumulus/environment'
